### ISSUE TITLE
NFS Provisioner broken in 4.8

### ISSUE THREAD

**Issue by gnunn1** [luisarizmendi/ocp-libvirt-ipi-role#14]
As an FYI the NFS Provisioner doesn't work in OCP 4.8 due to the removal of the selfLink feature from Kubernetes. Looking at switching to the NFS SubDirectory provisioner and will submit a PR when done.

https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

**Comment by luisarizmendi** [comment]
Great!, Thanks for the info...I tested libvirt IPI 4.8 install but not PVs so I was not yet aware of this problem

**Comment by gnunn1** [comment]
Actually it may be awhile for me to the PR, I ended up just deploying the subdir provisioner and moving the registry over to it and it works fine. Next time I do a fresh install I'll look at fixing this if someone doesn't beat me to it.

BTW thanks very much for this playbook, it's really useful and I appreciate the effort it takes to put it together and make it available to others.

**Comment by luisarizmendi** [comment]
Today I had some time and I changed the post-install OpenShift template that I use to deploy the nfs provisioned using the nfs-subdir-external-provisioner, it seems to be working now, thanks for pointing out the issue!
