### ISSUE TITLE
Is it possible to get Terraform + Openshift/libvirt to create VMs with hugepages?

### ISSUE THREAD

**Issue by ElCoyote27** [luisarizmendi/ocp-libvirt-ipi-role#6]
Hi Luis,

On my hypervisors, I have most of the memory dedicated to hugepages (the default 2Mb hugepages).
This allows me to fit more VMs into reserved memory and makes their TLB's smaller.

Here's an example:
```
# virsh dumpxml sat6|head -24
<domain type='kvm' id='3'>
  <name>sat6</name>
[...]
  <memoryBacking>
    <hugepages/>
  </memoryBacking>
[...]
```

I've done some research and it appears that Terraform has support for hugepages but I wouldn't know where to change it in the openshift installer.. Do you have any idea of where that might be?

**Comment by luisarizmendi** [comment]
Sorry, I missed this one!, no idea, but take a look to this repo from a guy that made it work: https://github.com/MonolithProjects/terraform-libvirt-vm
